In [2]:
import pandas as pd

### Dataframe
1. pd.Dataframe()
2. Heterogeneous
3. Ordered
4. Mutable, Size-Mutable
5. Dupication allowed
6. Customizable indexing, row & columes names
7. we use nested list rows
8. we use dict for cloumes

In [3]:
df = pd.DataFrame([[101,'Tejpal',50000],
                   [102,'Rohit',60000],
                   [103,'Raj',40000]], 
                   columns=['ID', 'NAME' ,'SALARY'])

In [4]:
df

    ID    NAME  SALARY
0  101  Tejpal   50000
1  102   Rohit   60000
2  103     Raj   40000

In [5]:
df.set_index('ID')

       NAME  SALARY
ID
101  Tejpal   50000
102   Rohit   60000
103     Raj   40000

In [6]:
df

    ID    NAME  SALARY
0  101  Tejpal   50000
1  102   Rohit   60000
2  103     Raj   40000

In [7]:
df2 = pd.DataFrame({'ID':[101,102,103,104],
                    'NAME':['Rohit','Virat','Raj','Don'],
                    'SALARY':[5000,4000,3000,7000]})

In [8]:
df2

    ID   NAME  SALARY
0  101  Rohit    5000
1  102  Virat    4000
2  103    Raj    3000
3  104    Don    7000

In [13]:
datasets = pd.read_csv("C:/Users/Omkar Pawar/OneDrive/Desktop/FBS/Data anlysis/Datasets/cars93.csv")

In [14]:
datasets

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver & Passenger,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,Driver & Passenger,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,Driver & Passenger,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [18]:
datasets = pd.read_csv("C:/Users/Omkar Pawar/OneDrive/Desktop/FBS/Data anlysis/Datasets/Top 10 IT Companies.csv")

In [20]:
datasets

         Top 10 IT Companies
0                        TCS
1                    Infosys
2              Tech Mahindra
3                      Wipro
4           HCL Technologies
5               L&T Infotech
6                   Mindtree
7                    Mphasis
8  Oracle Financial Services
9                Rotla India