In [3]:
import pandas as pd

In [7]:
data =pd.read_csv("C:/Users/Omkar Pawar/OneDrive/Desktop/FBS/Data anlysis/Datasets/student_10.csv")

In [11]:
data

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [12]:
data.info() ##provied infromation of file

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [9]:
data.describe()

        Student ID      Class  Study hrs  Percentage
count     7.000000  10.000000   8.000000    7.000000
mean   1006.000000  11.100000   4.375000   72.142857
std       3.464102   0.875595   3.020761   15.236235
min    1001.000000  10.000000   0.000000   50.000000
25%    1003.500000  10.250000   2.750000   60.000000
50%    1007.000000  11.000000   4.000000   80.000000
75%    1008.500000  12.000000   6.000000   82.500000
max    1010.000000  12.000000  10.000000   90.000000

In [13]:
data.shape ## to check how many rows and columes

(10, 5)

data.head is passing attributes,,,,
data.head() is called method

In [14]:
type(data)

pandas.DataFrame

In [15]:
data.size #how many values ,total values

50

In [16]:
data.head(3)

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0

In [17]:
data.tail()

         Date  Student ID  Class  Study hrs  Percentage
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [18]:
data.isna().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [19]:
data.dropna()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [20]:
data.dropna(inplace=True,axis=1)

C:\Users\Omkar Pawar\AppData\Local\Temp\ipykernel_3004\1729051458.py:1: Pandas4Warning: The inplace keyword in DataFrame.dropna is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  data.dropna(inplace=True,axis=1)

In [ ]:
data

In [21]:
data =pd.read_csv("C:/Users/Omkar Pawar/OneDrive/Desktop/FBS/Data anlysis/Datasets/student_10.csv")

In [22]:
data.isna().sum()

Date          0
Student ID    3
Class         0
Study hrs     2
Percentage    3
dtype: int64

In [23]:
data['Class']

0    10
1    10
2    10
3    11
4    11
5    11
6    12
7    12
8    12
9    12
Name: Class, dtype: int64

In [24]:
data['Class'].mean()

np.float64(11.1)

In [25]:
data['Class'].sum()

np.int64(111)

In [26]:
data['Class'].unique()

array([10, 11, 12])

In [29]:
data['Class'].value_counts()

Class
12    4
10    3
11    3
Name: count, dtype: int64

In [30]:
data.columns

Index(['Date', 'Student ID', 'Class', 'Study hrs', 'Percentage'], dtype='str')

In [31]:
data['Study hrs'] > 4.0

0    False
1     True
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9     True
Name: Study hrs, dtype: bool

In [33]:
df2 = data[data['Study hrs'] > 4.0]

In [34]:
df2

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
5  08-07-2021         NaN     11       10.0         NaN
9  12-07-2021      1010.0     12        6.0        85.0

In [35]:
data['Study hrs'].agg(['min', 'max', 'sum'])

min     0.0
max    10.0
sum    35.0
Name: Study hrs, dtype: float64